-- MySQL Script generated by MySQL Workbench
-- 22:28:22, 07 Fevral, 2017 yil, Seshanba
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lostandfound
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lostandfound
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lostandfound` DEFAULT CHARACTER SET utf8 ;
USE `lostandfound` ;

-- -----------------------------------------------------
-- Table `lostandfound`.`auth_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lostandfound`.`auth_rule` (
  `name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `data` BLOB NULL DEFAULT NULL,
  `created_at` INT(11) NULL DEFAULT NULL,
  `updated_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `lostandfound`.`auth_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lostandfound`.`auth_item` (
  `name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `type` SMALLINT(6) NOT NULL,
  `description` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `rule_name` VARCHAR(64) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `data` BLOB NULL DEFAULT NULL,
  `created_at` INT(11) NULL DEFAULT NULL,
  `updated_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`name`),
  INDEX `rule_name` (`rule_name` ASC),
  INDEX `idx-auth_item-type` (`type` ASC),
  CONSTRAINT `auth_item_ibfk_1`
    FOREIGN KEY (`rule_name`)
    REFERENCES `lostandfound`.`auth_rule` (`name`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `lostandfound`.`auth_assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lostandfound`.`auth_assignment` (
  `item_name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `user_id` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `created_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`item_name`, `user_id`),
  CONSTRAINT `auth_assignment_ibfk_1`
    FOREIGN KEY (`item_name`)
    REFERENCES `lostandfound`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `lostandfound`.`auth_item_child`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lostandfound`.`auth_item_child` (
  `parent` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `child` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`parent`, `child`),
  INDEX `child` (`child` ASC),
  CONSTRAINT `auth_item_child_ibfk_1`
    FOREIGN KEY (`parent`)
    REFERENCES `lostandfound`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `auth_item_child_ibfk_2`
    FOREIGN KEY (`child`)
    REFERENCES `lostandfound`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `lostandfound`.`migration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lostandfound`.`migration` (
  `version` VARCHAR(180) NOT NULL,
  `apply_time` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lostandfound`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lostandfound`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `auth_key` VARCHAR(32) CHARACTER SET 'utf8' NOT NULL,
  `password_hash` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `password_reset_token` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `status` SMALLINT(6) NOT NULL DEFAULT '10',
  `created_at` INT(11) NOT NULL,
  `updated_at` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC),
  UNIQUE INDEX `email` (`email` ASC),
  UNIQUE INDEX `password_reset_token` (`password_reset_token` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `lostandfound`.`post_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lostandfound`.`post_category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  `description` VARCHAR(255) NULL,
  `state` ENUM('draft', 'published') NULL DEFAULT 'draft',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lostandfound`.`post_lost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lostandfound`.`post_lost` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL,
  `description` VARCHAR(500) NOT NULL,
  `text` TEXT NULL,
  `created_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_dt` DATETIME NULL,
  `post_category_id` INT UNSIGNED NULL,
  `state` ENUM('draft', 'moderated', 'published', 'deleted') NOT NULL DEFAULT 'draft',
  PRIMARY KEY (`id`),
  INDEX `fk_post_lost_user1_idx` (`user_id` ASC),
  INDEX `fk_post_lost_post_category1_idx` (`post_category_id` ASC),
  CONSTRAINT `fk_post_lost_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `lostandfound`.`user` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_post_lost_post_category1`
    FOREIGN KEY (`post_category_id`)
    REFERENCES `lostandfound`.`post_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Yo\'qotilgan buyumlar uchun.';


-- -----------------------------------------------------
-- Table `lostandfound`.`post_found`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lostandfound`.`post_found` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL,
  `description` VARCHAR(500) NOT NULL,
  `text` TEXT NULL,
  `created_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_dt` DATETIME NULL,
  `post_category_id` INT UNSIGNED NULL,
  `state` ENUM('draft', 'moderated', 'published', 'deleted') NOT NULL DEFAULT 'draft',
  PRIMARY KEY (`id`),
  INDEX `fk_post_found_user1_idx` (`user_id` ASC),
  INDEX `fk_post_found_post_category1_idx` (`post_category_id` ASC),
  CONSTRAINT `fk_post_found_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `lostandfound`.`user` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_post_found_post_category1`
    FOREIGN KEY (`post_category_id`)
    REFERENCES `lostandfound`.`post_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Topilgan buyumlar uchun.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
